'use client';
import { useState } from 'react';
import { ArrowLeft, CheckCircle2, Globe2, Ship, Search, ShieldCheck, ClipboardCheck, MessageCircle, Factory, Calculator, PackageCheck, Mail } from 'lucide-react';

const services=[['البحث عن الموردين','نحدد أفضل مصانع وموردين موثوقين حسب المنتج والميزانية.',Search],['التفاوض والشراء','نتواصل مع الموردين ونقارن الأسعار وMOQ والشروط.',MessageCircle],['فحص الجودة','فحص قبل الشحن، صور، فيديو، وتقرير واضح قبل اعتماد الطلب.',ShieldCheck],['الشحن والتخليص','بحري أو جوي مع متابعة حتى وصول الشحنة.',Ship],['التصنيع الخاص','White Label وتصميم تغليف للمنتجات المناسبة.',Factory],['إدارة كاملة','من الفكرة حتى التسليم النهائي في بلدك.',PackageCheck]];
const products=['مستلزمات طبية غير منظمة','Packaging Materials','Trigger Sprayers','Foam Pumps','Air Freshener Components','Plastic Components','منتجات منزلية','إلكترونيات وإكسسوارات','تجميل وعناية','منتجات متاجر إلكترونية','مستلزمات صيدليات','منتجات صناعية'];
const steps=['استشارة مجانية','تحليل المنتج','البحث عن الموردين','مقارنة العروض','طلب العينات','فحص الجودة','الشحن','التسليم النهائي'];
const faqs=['هل أحتاج سجل تجاري؟ يعتمد على المنتج والدولة والكمية، ونوضح لك ذلك قبل الطلب.','هل تشحنون للسودان؟ نعم، مع توجيه طلبات السودان لفريق واتساب السودان.','هل تشحنون للسعودية؟ نعم، مع مراعاة متطلبات الجمارك وSABER عند الحاجة.','هل تتعاملون مع Alibaba؟ نعم، ونقارن أيضًا بين موردين آخرين عند الحاجة.','هل تضمنون الجودة؟ نقدم فحصًا وتقريرًا قبل الشحن، لكن الضمان النهائي حسب المورد والاتفاق.','هل أستطيع طلب عينات فقط؟ نعم، وهذا أفضل خيار في البداية.','هل تستوردون أدوية؟ لا ننصح بالبدء بالأدوية أو المنتجات المنظمة دون تراخيص واضحة.','كيف يتم الدفع؟ الأفضل أن يدفع العميل للمورد/الشحن مباشرة قدر الإمكان، ونحن نأخذ رسوم الخدمة.'];

export default function Home(){
 const [form,setForm]=useState({country:'السعودية',name:'',phone:'',email:'',product:'',quantity:'',budget:'',details:''});
 const [loading,setLoading]=useState(false); const [msg,setMsg]=useState('');
 const update=(k:string,v:string)=>setForm({...form,[k]:v});
 async function submit(e:React.FormEvent){e.preventDefault(); setLoading(true); setMsg(''); try{const res=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); const data=await res.json(); if(!res.ok) throw new Error(data.error||'حدث خطأ'); setMsg('تم حفظ الطلب. سيتم فتح واتساب الآن.'); if(data.whatsappUrl) window.open(data.whatsappUrl,'_blank');}catch(err:any){setMsg('تعذر الإرسال الآن. سيتم فتح واتساب مباشرة.'); const phone=form.country==='السودان'?'249117479767':'966530323512'; window.open(`https://wa.me/${phone}?text=${encodeURIComponent('مرحباً ChinaHere، أريد استشارة استيراد من الصين')}`,'_blank');}finally{setLoading(false)}}
 return <main className="min-h-screen overflow-hidden bg-[radial-gradient(circle_at_top,#15264a_0,#07111f_45%,#050914_100%)] text-white">
  <nav className="sticky top-0 z-50 border-b border-white/10 bg-navy/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a className="text-2xl font-black tracking-tight">China<span className="goldText">Here</span><span className="block text-xs font-medium text-white/55">Sourcing & Supply Chain Solutions</span></a><div className="hidden gap-6 text-sm text-white/70 md:flex"><a href="#services">الخدمات</a><a href="#process">الخطوات</a><a href="#form">طلب استشارة</a></div><a href="#form" className="rounded-full bg-gold px-5 py-2 font-bold text-navy">ابدأ الآن</a></div></nav>
  <section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 md:grid-cols-2 md:py-24"><div><div className="mb-5 inline-flex rounded-full border border-gold/30 px-4 py-2 text-gold">الصين هنا — استيراد أسهل وأوضح</div><h1 className="text-5xl font-black leading-tight md:text-7xl">الصين هنا.<br/><span className="goldText">استورد بثقة</span><br/>وبدون تعقيد.</h1><p className="mt-6 max-w-2xl text-lg leading-9 text-white/70">نساعدك في الوصول إلى أفضل الموردين في الصين، ونتولى البحث، المقارنة، التفاوض، الفحص، الشحن، والتخليص حتى وصول الشحنة إلى السعودية أو السودان.</p><div className="mt-8 flex flex-wrap gap-4"><a href="#form" className="rounded-2xl bg-gold px-7 py-4 font-black text-navy shadow-gold">احصل على استشارة مجانية</a><a href="#process" className="rounded-2xl border border-white/15 px-7 py-4 font-bold">كيف نعمل؟</a></div><div className="mt-10 grid grid-cols-2 gap-4 md:grid-cols-4">{[['السعودية والسودان','تغطية'],['فحص قبل الشحن','جودة'],['عينات أولًا','مخاطرة أقل'],['واتساب مباشر','تواصل سريع']].map((x,i)=><div className="glass rounded-2xl p-4" key={i}><b className="text-xl text-gold">{x[0]}</b><p className="text-sm text-white/55">{x[1]}</p></div>)}</div></div><div className="glass rounded-[2rem] p-6 shadow-2xl"><div className="rounded-[1.5rem] bg-white/5 p-6"><Globe2 className="mb-4 h-12 w-12 text-gold"/><h2 className="text-2xl font-black">من المصنع الصيني إلى باب مستودعك</h2><p className="mt-3 leading-8 text-white/65">ابدأ بمنتج واحد أو عينة صغيرة. لا ننصح بالشحنات الكبيرة قبل اختبار المورد والجودة والتكلفة النهائية.</p><div className="mt-6 space-y-3">{['بحث موردين موثوقين','مقارنة أسعار وشروط','تقرير فحص واضح','توجيه واتساب حسب الدولة'].map(t=><p key={t} className="flex items-center gap-2"><CheckCircle2 className="text-gold"/> {t}</p>)}</div></div></div></section>
  <section id="services" className="mx-auto max-w-7xl px-5 py-16"><h2 className="text-4xl font-black">كل ما تحتاجه تحت سقف واحد</h2><p className="mt-3 text-white/60">خدمات عملية للبدء بأقل مخاطرة ممكنة.</p><div className="mt-8 grid gap-5 md:grid-cols-3">{services.map(([title,desc,Icon]:any)=><div className="glass rounded-3xl p-6" key={title}><Icon className="mb-5 h-10 w-10 text-gold"/><h3 className="text-xl font-black">{title}</h3><p className="mt-3 leading-7 text-white/60">{desc}</p></div>)}</div></section>
  <section id="process" className="bg-white/[.03] py-16"><div className="mx-auto max-w-7xl px-5"><h2 className="text-4xl font-black">خطوات بسيطة للحصول على بضاعتك</h2><div className="mt-8 grid gap-4 md:grid-cols-4">{steps.map((s,i)=><div className="glass rounded-3xl p-5" key={s}><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-gold font-black text-navy">{i+1}</div><h3 className="font-black">{s}</h3></div>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-16"><h2 className="text-4xl font-black">منتجات نساعدك في توريدها</h2><div className="mt-8 grid gap-3 md:grid-cols-4">{products.map(p=><div className="rounded-2xl border border-white/10 bg-white/5 p-4 text-center text-white/75" key={p}>{p}</div>)}</div></section>
  <section className="mx-auto grid max-w-7xl gap-6 px-5 py-16 md:grid-cols-2"><div className="glass rounded-3xl p-8"><Calculator className="mb-4 text-gold"/><h2 className="text-3xl font-black">قاعدة البداية الآمنة</h2><p className="mt-4 leading-9 text-white/65">لا تبدأ بكونتينر. ابدأ بعينات أو طلبية صغيرة، احسب التكلفة النهائية: سعر المنتج + الشحن + الجمارك + التخزين + النقل + التالف. الربح الحقيقي يظهر بعد وصول البضاعة وبيعها.</p></div><div className="glass rounded-3xl p-8"><ClipboardCheck className="mb-4 text-gold"/><h2 className="text-3xl font-black">تنبيه مهم</h2><p className="mt-4 leading-9 text-white/65">ChinaHere تقدم خدمة بحث وتنسيق وفحص وشحن. قبول المنتجات جمركيًا أو احتياجها لتراخيص يعتمد على نوع المنتج والدولة والأنظمة المعمول بها.</p></div></section>
  <section className="bg-white/[.03] py-16"><div className="mx-auto max-w-5xl px-5"><h2 className="text-4xl font-black">أسئلة شائعة</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{faqs.map((f,i)=><div className="glass rounded-2xl p-5" key={i}>{f}</div>)}</div></div></section>
  <section id="form" className="mx-auto max-w-4xl px-5 py-20"><div className="glass rounded-[2rem] p-6 md:p-10"><Mail className="mb-4 h-10 w-10 text-gold"/><h2 className="text-4xl font-black">اطلب استشارة استيراد</h2><p className="mt-3 text-white/60">اختر الدولة أولًا ليتم توجيهك للرقم الصحيح.</p><form onSubmit={submit} className="mt-8 grid gap-4 md:grid-cols-2"><select value={form.country} onChange={e=>update('country',e.target.value)} className="rounded-2xl border border-white/10 bg-white/5 p-4 md:col-span-2"><option>السعودية</option><option>السودان</option></select><input required placeholder="الاسم الكامل" value={form.name} onChange={e=>update('name',e.target.value)} className="rounded-2xl border border-white/10 bg-white/5 p-4"/><input required placeholder="رقم الجوال" value={form.phone} onChange={e=>update('phone',e.target.value)} className="rounded-2xl border border-white/10 bg-white/5 p-4"/><input placeholder="البريد الإلكتروني" value={form.email} onChange={e=>update('email',e.target.value)} className="rounded-2xl border border-white/10 bg-white/5 p-4"/><input required placeholder="نوع المنتج" value={form.product} onChange={e=>update('product',e.target.value)} className="rounded-2xl border border-white/10 bg-white/5 p-4"/><input placeholder="الكمية التقريبية" value={form.quantity} onChange={e=>update('quantity',e.target.value)} className="rounded-2xl border border-white/10 bg-white/5 p-4"/><input placeholder="الميزانية التقريبية" value={form.budget} onChange={e=>update('budget',e.target.value)} className="rounded-2xl border border-white/10 bg-white/5 p-4"/><textarea placeholder="تفاصيل إضافية" value={form.details} onChange={e=>update('details',e.target.value)} className="min-h-32 rounded-2xl border border-white/10 bg-white/5 p-4 md:col-span-2"/><button disabled={loading} className="rounded-2xl bg-gold p-4 font-black text-navy md:col-span-2">{loading?'جاري الإرسال...':'أرسل الطلب وافتح واتساب'} <ArrowLeft className="inline"/></button>{msg&&<p className="text-gold md:col-span-2">{msg}</p>}</form></div></section>
  <footer className="border-t border-white/10 px-5 py-10 text-center text-white/50"><b className="text-white">ChinaHere</b><br/>Sourcing & Supply Chain Solutions<br/>chinahere.import@gmail.com</footer>
 </main>
}
